name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags:
        - 'v*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push 1
        uses: docker/build-push-action@v2
        with:
          context: service1
          file: ./service1/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/service1:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/service1:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/service1:buildcache,mode=max
      -  
        name: Build and push 2
        uses: docker/build-push-action@v2
        with:
          context: service2
          file: ./service2/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/service2:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/service2:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/service2:buildcache,mode=max
