name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - 
        name: Get latest tag
        id: latest_tag
        uses: jacobtomlinson/gha-get-docker-hub-tags@0.1.1
        with:
          org: ${{ secrets.DOCKER_HUB_USERNAME }}
          repo: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - 
        name: Check outputs
        run: |
          echo "Latest Image Tag - ${{ steps.latest_tag.outputs.tag }}"
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push 1
        uses: docker/build-push-action@v2
        with:
          context: service1
          file: ./service1/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/service1:
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/service1:latest
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/service1:latest,mode=max
      -  
        name: Build and push 2
        uses: docker/build-push-action@v2
        with:
          context: service2
          file: ./service2/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/service2
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/service2:latest
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/service2:latest,mode=max
