name: Docker Image CI


on:
  push:
    branches: [ "main" ]
    
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - 
        name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            docker.io/${{secrets.DOCKER_HUB_USERNAME}}/service1
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          flavor: |
            latest=true
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push 1
        uses: docker/build-push-action@v2
        with:
          context: service1
          file: ./service1/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/service1:${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/service1:latest
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/service1:${{ steps.meta.outputs.tags }},mode=max
      -  
        name: Build and push 2
        uses: docker/build-push-action@v2
        with:
          context: service2
          file: ./service2/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/service2:${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/service2:latest
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/service2:${{ steps.meta.outputs.tags }},mode=max
